### ISSUE TITLE
Format code does not work if a style element is added

### ISSUE THREAD

**Issue by chaspi** [mjbvz/vscode-lit-html#59] opened 2018-12-23 15:15 UTC
When using a style element inside the literal the code formatter stopps working. As soon the style element is removed the formatter works again.

```
html`
    <style></style>
    <div>
        <div>test</div>
    </div>
`
```

**Comment by mjbvz** [comment] 2019-01-03 01:00
Duplicate of https://github.com/Microsoft/typescript-lit-html-plugin/issues/16

**Closed by mjbvz** 2019-01-03 01:00 UTC
