### ISSUE TITLE
Support css syntax highlighting in template literal

### ISSUE THREAD

**Issue by dustensalinas** [mjbvz/vscode-lit-html#66] opened 2019-02-26 19:26 UTC
For example:

```
class MyElement extends LitElement {
  static styles = css`
    :host {
      display: block;
    }
  `;
}
```

Adding css to the literal tags setting works great but unfortunately does not perform css syntax highlighting without the <style tag>.  We'll see if I'm able to get to this myself and do a PR but wanted to know any thoughts or in progress work on this if there was any.

**Comment by mjbvz** [comment] 2019-02-26 19:29
Duplicate of #60

Install https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components for this

**Closed by mjbvz** 2019-02-26 19:29 UTC

**Comment by Anthony-As** [comment] 2020-02-29 05:01
muchas gracias por tu aporte
