### ISSUE TITLE
Add emmet support inside html template tag

### ISSUE THREAD

**Issue by joslarson** [mjbvz/vscode-lit-html#19] opened 2018-02-08 00:04 UTC
I tried to dig into this myself, but couldn't find anything on it, so it might not be possible (not sure), but it would be nice if emmet worked inside the html template tagged literal.

**Comment by mikeleonard** [comment] 2018-05-23 07:59
This looks relevant: 
https://github.com/Microsoft/typescript-lit-html-plugin/issues/2

**Comment by mjbvz** [comment] 2018-07-03 21:22
Duplicate of https://github.com/Microsoft/typescript-lit-html-plugin/issues/2

**Closed by mjbvz** 2018-07-03 21:22 UTC
